"""String templates for notebook cells. Each function returns a (cell_type,
source) tuple. Kept as plain string templates rather than a templating
engine (Jinja etc.) since the substitutions are simple and this keeps the
dependency footprint small — revisit if templates grow complex."""

from __future__ import annotations


def title_markdown(model_path: str) -> tuple[str, str]:
    return "markdown", f"""# Fine-tuning Notebook

Generated by LLM Architecture Explorer.

**Base model:** `{model_path}`
**Task:** Causal language modeling (fine-tuning)

This notebook was assembled automatically based on the architecture,
pruning, and PEFT configuration selected in the explorer. All cells are
fully editable — nothing here is locked.
"""


def install_deps_code() -> tuple[str, str]:
    return "code", """# Dependencies
# !pip install transformers datasets peft accelerate bitsandbytes trl
"""


def imports_code() -> tuple[str, str]:
    return "code", """import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer
"""


def load_model_code(model_path: str) -> tuple[str, str]:
    return "code", f"""# Load base model and tokenizer
MODEL_PATH = {model_path!r}

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.bfloat16,   # adjust to your hardware (float16 / float32 as needed)
    device_map="auto",
)
"""


def dataset_placeholder_code() -> tuple[str, str]:
    return "code", """# ---------------------------------------------------------------
# Dataset loading — fill this in.
#
# Example:
#   dataset = load_dataset("your_dataset_name", split="train")
#
# The dataset should have a text field the tokenizer can consume, or you
# can define a formatting function and pass it to SFTTrainer below via
# `formatting_func`.
# ---------------------------------------------------------------

dataset = None  # TODO: load your dataset here
"""


def pruning_notice_markdown(pruned_node_names: list[str]) -> tuple[str, str]:
    listed = "\n".join(f"- `{name}`" for name in pruned_node_names)
    return "markdown", f"""## Note on pruning

The following modules were marked as pruned in the explorer:

{listed}

**Structural pruning (actually removing these modules from the model) is
not yet implemented in code generation.** This notebook trains the full,
unpruned model. Pruning support will be added in a future version —
for now, treat the prune markers as a design note, not an applied change.
"""

def pruning_code(pruned_layer_indices: list[int], sub_layer_prune_warnings: list[str]) -> tuple[str, str]:
    """Generates code to remove entire decoder layers from model.layers,
    for pruned nodes that map to a full layer index (e.g. model.layers.7).

    Sub-layer-level prune selections (e.g. pruning just self_attn or a
    single q_proj within an otherwise-active layer) CANNOT be safely
    codegenerated this way — LlamaMLP.forward() and similar have hardcoded
    references to gate_proj/up_proj/down_proj etc., so removing a submodule
    without rewriting forward() would break the model. Those are flagged
    as warnings, not silently applied.
    """
    if not pruned_layer_indices and not sub_layer_prune_warnings:
        return "code", "# No layers pruned.\n"

    warning_lines = ""
    if sub_layer_prune_warnings:
        listed = "\n".join(f"#   - {w}" for w in sub_layer_prune_warnings)
        warning_lines = (
            "# NOTE: the following pruned selections are SUB-LAYER level "
            "(e.g. a single attention or MLP projection within an otherwise-\n"
            "# active decoder layer). These are NOT applied below — removing a\n"
            "# submodule without rewriting the layer's forward() method would\n"
            "# break the model. Only whole-layer pruning is auto-applied.\n"
            f"{listed}\n\n"
        )

    if not pruned_layer_indices:
        return "code", warning_lines + "# No whole layers pruned — only unsupported sub-layer prunes were selected (see note above).\n"

    indices_str = ", ".join(str(i) for i in sorted(pruned_layer_indices))
    code = f"""{warning_lines}# Remove pruned decoder layers entirely, BEFORE applying PEFT.
pruned_layer_indices = [{indices_str}]

# Different architectures store the block list under different attribute
# paths (Llama/Gemma/Qwen: model.model.layers; GPT-2: model.transformer.h).
# Try known patterns rather than assuming one.
if hasattr(model, "model") and hasattr(model.model, "layers"):
    container_obj, attr_name = model.model, "layers"
elif hasattr(model, "transformer") and hasattr(model.transformer, "h"):
    container_obj, attr_name = model.transformer, "h"
elif hasattr(model, "layers"):
    container_obj, attr_name = model, "layers"
elif hasattr(model, "h"):
    container_obj, attr_name = model, "h"
else:
    raise RuntimeError(
        "Could not locate the decoder layer list on this model "
        "(checked model.model.layers, model.transformer.h, model.layers, model.h). "
        "Pruning codegen doesn't yet support this architecture's naming convention — "
        "prune manually or adjust this cell."
    )

layers_attr = getattr(container_obj, attr_name)
kept_layers = [layer for i, layer in enumerate(layers_attr) if i not in pruned_layer_indices]
import torch.nn as nn
setattr(container_obj, attr_name, nn.ModuleList(kept_layers))

if hasattr(model.config, "num_hidden_layers"):
    model.config.num_hidden_layers = len(kept_layers)

print(f"Pruned {{len(pruned_layer_indices)}} layer(s): {{pruned_layer_indices}}")
print(f"Remaining layers: {{len(kept_layers)}}")
"""
    return "code", code


def peft_config_code(peft_targets: list[tuple["LayerNode", "PeftConfig"]]) -> tuple[str, str]:
    """peft_targets: list of (LayerNode, PeftConfig) for nodes marked
    PEFT_TARGET. Takes the actual LayerNode (not just its name) so we can
    check module_type — needed to detect GPT-2-style Conv1D layers, which
    require fan_in_fan_out=True in peft's LoraConfig due to their
    transposed weight storage convention.
    """
    if not peft_targets:
        return "code", "# No PEFT targets selected — this will fine-tune the FULL model.\npeft_config = None\n"

    import re

    target_module_names = sorted({node.local_name for node, _cfg in peft_targets})

    layer_indices = set()
    has_non_layer_target = False
    for node, _cfg in peft_targets:
        match = re.search(r"\.(layers|h)\.(\d+)\.", node.name)
        if match:
            layer_indices.add(int(match.group(2)))
        else:
            has_non_layer_target = True

    has_conv1d = any(node.module_type == "Conv1D" for node, _cfg in peft_targets)
    has_linear = any(node.module_type == "Linear" for node, _cfg in peft_targets)

    methods_used = {cfg.method for _node, cfg in peft_targets}
    unsupported = methods_used - {"LoRA", "QLoRA", "DoRA"}

    warning_comment = ""
    if unsupported:
        warning_comment += (
            f"# NOTE: methods {sorted(unsupported)} were selected for some targets "
            f"but are not yet supported in codegen (only LoRA/QLoRA/DoRA are). "
            f"Those targets are included below using LoRA as a fallback.\n"
        )
    if len(methods_used) > 1:
        warning_comment += (
            f"# NOTE: multiple PEFT methods were selected across targets ({sorted(methods_used)}). "
            f"peft.LoraConfig applies one rank/alpha/dropout to all target_modules — "
            f"using the first target's values as representative.\n"
        )
    if has_non_layer_target:
        warning_comment += (
            f"# NOTE: some selected targets aren't part of the repeated layer stack, "
            f"so layers_to_transform doesn't apply to them.\n"
        )
    if layer_indices:
        warning_comment += (
            f"# NOTE: layers_to_transform relies on peft's layer-index matching, which has "
            f"been reported unreliable on some peft/transformers version combinations "
            f"(see https://github.com/huggingface/peft/issues/2155). Verify "
            f"model.print_trainable_parameters() below shows the expected count.\n"
        )
    if has_conv1d and has_linear:
        warning_comment += (
            f"# WARNING: selected targets mix Conv1D (e.g. GPT-2 style c_attn/c_proj) and "
            f"standard Linear modules. fan_in_fan_out=True is required for Conv1D targets but "
            f"WRONG for Linear targets — peft.LoraConfig only accepts one value for the whole "
            f"config. This mixed selection cannot be correctly codegenerated as a single "
            f"LoraConfig; consider targeting only one module type at a time.\n"
        )
    elif has_conv1d:
        warning_comment += (
            f"# NOTE: target(s) use Conv1D (GPT-2-style fused/transposed weight layout), "
            f"so fan_in_fan_out=True is set below — required for LoRA to work correctly "
            f"with this layer type.\n"
        )

    rep_config = peft_targets[0][1]

    layers_arg = ""
    if layer_indices and not has_non_layer_target:
        sorted_layers = sorted(layer_indices)
        layers_arg = f",\n    layers_to_transform={sorted_layers!r}"

    fan_in_fan_out_arg = ""
    if has_conv1d and not has_linear:
        fan_in_fan_out_arg = ",\n    fan_in_fan_out=True"

    code = f"""{warning_comment}peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r={rep_config.rank},
    lora_alpha={rep_config.alpha},
    lora_dropout={rep_config.dropout},
    target_modules={target_module_names!r}{layers_arg}{fan_in_fan_out_arg}
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()  # VERIFY this matches your explorer's estimate
"""
    return "code", code

def training_args_code() -> tuple[str, str]:
    return "code", """training_args = TrainingArguments(
    output_dir="./output",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=10,
    save_strategy="epoch",
    bf16=True,   # adjust to your hardware
    report_to="none",
)
"""


def trainer_code() -> tuple[str, str]:
    return "code", """# ---------------------------------------------------------------
# NOTE: requires `dataset` to be set above (currently a placeholder).
# ---------------------------------------------------------------
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    tokenizer=tokenizer,
)

trainer.train()
"""


def save_and_export_code() -> tuple[str, str]:
    return "code", """# Save adapter (if PEFT was used) or full model
trainer.save_model("./output/final")
tokenizer.save_pretrained("./output/final")

# If using PEFT and you want a merged, standalone model:
# merged_model = model.merge_and_unload()
# merged_model.save_pretrained("./output/merged")
"""


def resource_summary_markdown(estimate) -> tuple[str, str]:
    return "markdown", f"""## Resource estimate (from explorer, at generation time)

| Metric | Value |
|---|---|
| Total params | {estimate.total_params:,} |
| Active params (after pruning) | {estimate.active_params:,} |
| Trainable params | {estimate.trainable_params:,} |
| Trainable % | {estimate.trainable_pct:.3f}% |
| Estimated VRAM (params + optimizer, excl. activations) | {estimate.estimated_vram_bytes / 1e9:.2f} GB |

These are estimates computed from the model's declared architecture and your
selected configuration — actual usage will vary with batch size, sequence
length, and dataset.
"""