"""String templates for notebook cells. Each function returns a (cell_type,
source) tuple. Kept as plain string templates rather than a templating
engine (Jinja etc.) since the substitutions are simple and this keeps the
dependency footprint small — revisit if templates grow complex."""

from __future__ import annotations


def title_markdown(model_path: str) -> tuple[str, str]:
    return "markdown", f"""# Fine-tuning Notebook

Generated by LLM Architecture Explorer.

**Base model:** `{model_path}`
**Task:** Causal language modeling (fine-tuning)

This notebook was assembled automatically based on the architecture,
pruning, and PEFT configuration selected in the explorer. All cells are
fully editable — nothing here is locked.
"""


def install_deps_code() -> tuple[str, str]:
    return "code", """# Dependencies
# !pip install transformers datasets peft accelerate bitsandbytes trl
"""


def imports_code() -> tuple[str, str]:
    return "code", """import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer
"""


def load_model_code(model_path: str) -> tuple[str, str]:
    return "code", f"""# Load base model and tokenizer
MODEL_PATH = {model_path!r}

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.bfloat16,   # adjust to your hardware (float16 / float32 as needed)
    device_map="auto",
)
"""


def dataset_placeholder_code() -> tuple[str, str]:
    return "code", """# ---------------------------------------------------------------
# Dataset loading — fill this in.
#
# Example:
#   dataset = load_dataset("your_dataset_name", split="train")
#
# The dataset should have a text field the tokenizer can consume, or you
# can define a formatting function and pass it to SFTTrainer below via
# `formatting_func`.
# ---------------------------------------------------------------

dataset = None  # TODO: load your dataset here
"""


def pruning_notice_markdown(pruned_node_names: list[str]) -> tuple[str, str]:
    listed = "\n".join(f"- `{name}`" for name in pruned_node_names)
    return "markdown", f"""## Note on pruning

The following modules were marked as pruned in the explorer:

{listed}

**Structural pruning (actually removing these modules from the model) is
not yet implemented in code generation.** This notebook trains the full,
unpruned model. Pruning support will be added in a future version —
for now, treat the prune markers as a design note, not an applied change.
"""


def peft_config_code(peft_targets: list[tuple[str, "PeftConfig"]]) -> tuple[str, str]:
    """peft_targets: list of (node_name, PeftConfig) for nodes marked PEFT_TARGET.

    Only LoRA/QLoRA/DoRA are supported for actual codegen right now, since
    those map onto peft library's LoraConfig with target_modules. Other
    methods (AdaLoRA, IA3, Prefix Tuning) are flagged, not generated,
    since they need separate config classes not yet wired up here.
    """
    if not peft_targets:
        return "code", "# No PEFT targets selected — this will fine-tune the FULL model.\npeft_config = None\n"

    # local_name (e.g. "q_proj") is what peft's target_modules expects,
    # not the fully-qualified name — collect unique local names.
    target_module_names = sorted({name.split(".")[-1] for name, _cfg in peft_targets})

    # All targets currently share one config in the UI (method/rank/alpha
    # per node, but peft's LoraConfig applies one rank/alpha across all
    # target_modules) — use the first target's config as representative,
    # and warn if configs actually differ across targets.
    methods_used = {cfg.method for _name, cfg in peft_targets}
    unsupported = methods_used - {"LoRA", "QLoRA", "DoRA"}

    warning_comment = ""
    if unsupported:
        warning_comment = (
            f"# NOTE: methods {sorted(unsupported)} were selected for some targets "
            f"but are not yet supported in codegen (only LoRA/QLoRA/DoRA are).\n"
            f"# Those targets are included in target_modules below using LoRA as a fallback.\n"
        )

    if len(methods_used) > 1:
        warning_comment += (
            f"# NOTE: multiple PEFT methods were selected across targets ({sorted(methods_used)}). "
            f"peft.LoraConfig applies one rank/alpha/dropout to all target_modules — "
            f"using the first target's values as representative. Adjust manually if needed.\n"
        )

    rep_config = peft_targets[0][1]

    code = f"""{warning_comment}peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r={rep_config.rank},
    lora_alpha={rep_config.alpha},
    lora_dropout={rep_config.dropout},
    target_modules={target_module_names!r},
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()
"""
    return "code", code


def training_args_code() -> tuple[str, str]:
    return "code", """training_args = TrainingArguments(
    output_dir="./output",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=10,
    save_strategy="epoch",
    bf16=True,   # adjust to your hardware
    report_to="none",
)
"""


def trainer_code() -> tuple[str, str]:
    return "code", """# ---------------------------------------------------------------
# NOTE: requires `dataset` to be set above (currently a placeholder).
# ---------------------------------------------------------------
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    tokenizer=tokenizer,
)

trainer.train()
"""


def save_and_export_code() -> tuple[str, str]:
    return "code", """# Save adapter (if PEFT was used) or full model
trainer.save_model("./output/final")
tokenizer.save_pretrained("./output/final")

# If using PEFT and you want a merged, standalone model:
# merged_model = model.merge_and_unload()
# merged_model.save_pretrained("./output/merged")
"""


def resource_summary_markdown(estimate) -> tuple[str, str]:
    return "markdown", f"""## Resource estimate (from explorer, at generation time)

| Metric | Value |
|---|---|
| Total params | {estimate.total_params:,} |
| Active params (after pruning) | {estimate.active_params:,} |
| Trainable params | {estimate.trainable_params:,} |
| Trainable % | {estimate.trainable_pct:.3f}% |
| Estimated VRAM (params + optimizer, excl. activations) | {estimate.estimated_vram_bytes / 1e9:.2f} GB |

These are estimates computed from the model's declared architecture and your
selected configuration — actual usage will vary with batch size, sequence
length, and dataset.
"""